id: IA2567FD4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T23:48:20+00:00'
last_modified: '2022-06-07T17:22:58.321637+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5555
  title: བར་དོ་ཐོས་གྲོལ་ཆེན་མོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
  base:
    4AA7:
      image_group_id: I3CN5557
      title: ''
      total_pages: 370
      order: 1
      base_file: 4AA7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
