id: P003073
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5555
  title: བར་དོ་ཐོས་གྲོལ་ཆེན་མོ།
  author: ''
  volumes:
    00bdd705efa7418a8b3411033fbc4a34:
      image_group_id: I3CN5557
      title: ''
      volume_number: 1
      total_pages: 370
