id: P003073
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 10:38:42.118739
source_metadata:
  id: bdr:W3CN5555
  title: བར་དོ་ཐོས་གྲོལ་ཆེན་མོ།
  author: ''
  volumes:
    00bdd705efa7418a8b3411033fbc4a34:
      image_group_id: I3CN5557
      title: ''
      volume_number: 1
      total_pages: 370
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
